apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-chart.fullname" . }}
  labels:
    {{- include "app-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: web
  selector:
    {{- include "app-chart.selectorLabels" . | nindent 4 }}
